### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by daymegr** [IanevskiAleksandr/sc-type#1]
Hi Aleksandr, 

I found the sc-type paper and I am pretty curious about trying the technique for cell-type identification you described on my own datasets. I couldn't find the code here. Can you let me know how to get it? 
Many thanks in advance. 
Daymé

**Comment by IanevskiAleksandr** [comment]
Dear @daymegr ,

Please find a source code here: https://github.com/IanevskiAleksandr/sc-type

BR,
Aleksandr
