### ISSUE TITLE
Using the integrated[["integrated"]]@scale.data slot... 

### ISSUE THREAD

**Issue by marencc** [IanevskiAleksandr/sc-type#13]
Hi! 
Many thanks for developing this tool. I have a question, as far as I understand, 
`integrated[["integrated"]]@scale.data`
should not be further used to classify, as stated[ here ](https://github.com/satijalab/seurat/issues/1717#issuecomment-504458665)by the seurat's developers 
But, now I am confused,  as on your example you suggest we may feed this slot into the tool...

**Comment by IanevskiAleksandr** [comment]
Hi @marencc,

Thanks for a nice question. You should not use "integrated" object for identifying differentially expressed (DE) genes between the conditions, and subsequent analyses based on those. However, ScType doesn't calculate DE genes and should provide quite a good approximation if you run it on integrated dataset. 

I tried running ScType on at least 5 integrated datasets, and was getting the same annotations, as if I would do it separately for each dataset in the integrated objects.

To be on the safe side, you can definitely run ScType separately for each data object you are going to integrated, and then combine the results, but I would expect it to be extremely similar to annotations made on the integrated object.

Kind regards,
Aleksandr
