### ISSUE TITLE
How to run in a silent mode?

### ISSUE THREAD

**Issue by hongjianjin** [IanevskiAleksandr/sc-type#16]
These messages are very annoying..... Is there anyway to run quiet and neatly ?

Maps last updated on: Thu Oct 24 12:31:05 2019
Maps last updated on: Thu Oct 24 12:31:05 2019
Maps last updated on: Thu Oct 24 12:31:05 2019
Maps last updated on: Thu Oct 24 12:31:05 2019
Maps last updated on: Thu Oct 24 12:31:05 2019
Maps last updated on: Thu Oct 24 12:31:05 2019
Maps last updated on: Thu Oct 24 12:31:05 2019
Maps last updated on: Thu Oct 24 12:31:05 2019
Maps last updated on: Thu Oct 24 12:31:05 2019
Maps last updated on: Thu Oct 24 12:31:05 2019
Maps last updated on: Thu Oct 24 12:31:05 2019
Maps last updated on: Thu Oct 24 12:31:05 2019
Maps last updated on: Thu Oct 24 12:31:05 2019
Maps last updated on: Thu Oct 24 12:31:05 2019
.....

**Comment by IanevskiAleksandr** [comment]
Suppressing of messages was implemented now, thanks)
