### ISSUE TITLE
Data visualization not working

### ISSUE THREAD

**Issue by selifeski** [IanevskiAleksandr/sc-type#2]
Dear,

I am having an issue on visualization of the data. Data processing step works fine. I can see the highly variable genes etc. However, in scatter plot section it just does not show anything, no matter which I click (see screenshot). And if choose to go back in processing step, I kept having  this window: Not Found  The requested URL was not found on this server. What could be the problem?

Thank you,

![image](https://user-images.githubusercontent.com/57804234/91550293-a2f2b480-e928-11ea-881e-0ed6b8f70423.png)

![image](https://user-images.githubusercontent.com/57804234/91550259-9706f280-e928-11ea-8b7e-f66fb001b66e.png)

![image](https://user-images.githubusercontent.com/57804234/91550041-37a8e280-e928-11ea-8c11-0335adeaaab2.png)

**Comment by hildegarda-k** [comment]
Hello, 
I have the same issue, I triple checked the imput data and could not find the solution. Have you solved it in the end? I was thinking it might be because my dataset is quite large (almost 0.5 GB, but x10 sequencing is large...)

**Comment by IanevskiAleksandr** [comment]
@selifeski, @hildegarda-k , thank you for your replies. It should be working fine now.

**Comment by IanevskiAleksandr** [comment]
@selifeski , @hildegarda-k , thank you for your replies. It should be working fine now.
