### ISSUE TITLE
Error: Failed to install 'unknown package' from GitHub

### ISSUE THREAD

**Issue by akhst7** [IanevskiAleksandr/sc-type#20]
HI, 
I can't install sc-type from a GitHub repo with a following error;

```
> remotes::install_github("LanevskiAleksandr/sc-type")
Using github PAT from envvar GITHUB_PAT
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found
```

or from local;

```
remotes::install_local("~/Downloads/sc-type.tar.gz", type = "source", repos = NULL)
Error: Failed to install 'sc-type.tar.gz' from local:
  Does not appear to be an R package (no DESCRIPTION)
```

HTTP 404 error is typically a lack of a package description as local install error suggests.

**Comment by IanevskiAleksandr** [comment]
Hi @akhst7,

You do not need to install. Instead, follow https://github.com/IanevskiAleksandr/sc-type#readme

Kind regards,
**I**anevski Aleksandr
