### ISSUE TITLE
'Rcpp_precious_remove' not provided by package 'Rcpp'

### ISSUE THREAD

**Issue by ChaseTaylor939** [IanevskiAleksandr/sc-type#22]
I apologize if this is a simple fix I'm just not seeing.  I keep getting the same error when I try to run my data through the tutorial.  I get the following error when I run this line of code, "gs_list = gene_sets_prepare(db_, tissue)".

Error in getChildlessNode(xml = workbookRelsXML, tag = "Relationship"): function 'Rcpp_precious_remove' not provided by package 'Rcpp'
Traceback:

1. gene_sets_prepare(db_, tissue)
2. openxlsx::read.xlsx(path_to_db_file)
3. read.xlsx.default(path_to_db_file)
4. getChildlessNode(xml = workbookRelsXML, tag = "Relationship")

**Comment by IanevskiAleksandr** [comment]
Reinstalling the package Rcpp should solve the problem:
`install.packages('Rcpp')
`

**Comment by ChaseTaylor939** [comment]
Thank you for your quick reply!  I apologize, but I keep having the same issue.  I am still a beginner, and I'm having trouble figuring this out.  Any insight is greatly appreciated.  Am I using the wrong version maybe?  When I run install.packages('Rcpp') I get the following message, but the session info says I'm running Rcpp_1.0.6:



Installing package into 'C:/Users/taylor81/Documents/R/win-library/4.1'
(as 'lib' is unspecified)


  There is a binary version available but the source version is later:
     binary source needs_compilation
Rcpp  1.0.9 1.0.10              TRUE

installing the source package 'Rcpp'


Warning message in install.packages("Rcpp"):
"installation of package 'Rcpp' had non-zero exit status"

**Comment by IanevskiAleksandr** [comment]
Did you try to upload the latest version of R and running the installation process there? https://cran.r-project.org/bin/windows/base/
