### ISSUE TITLE
Quickstart - Missing dependency "openxlsx"

### ISSUE THREAD

**Issue by aerickso** [IanevskiAleksandr/sc-type#23]
Hi!

Thank you for developing sc-type.

In re-running your quick-start guide, I received the error "#Error in loadNamespace(x) : there is no package called ‘openxlsx’.

Here's a revised first line that allowed me to run the rest of the code automatically.

`lapply(c("dplyr","Seurat","HGNChelper", "openxlsx"), library, character.only = T)
`

**Comment by IanevskiAleksandr** [comment]
Thanks, included.
