### ISSUE TITLE
Is it suitable for lung cancer scRNA-seq analysis?

### ISSUE THREAD

**Issue by wisRen** [IanevskiAleksandr/sc-type#28]
We know that lung cancer may contain lung cancer cells, TME cells, including immuno-cells, how should I select the tissue types?
`tissue = "Lung" # e.g. Immune system,Pancreas,Liver,Eye,Kidney,Brain,Lung,Adrenal,Heart,Intestine,Muscle,Placenta,Spleen,Stomach,Thymus `
`tissue = "Immune system" # e.g. Immune system,Pancreas,Liver,Eye,Kidney,Brain,Lung,Adrenal,Heart,Intestine,Muscle,Placenta,Spleen,Stomach,Thymus `

Above, we used Lung or Immune system, they final figure give different cell type annoation. There are some cell type overlap, and an unknown cell type with [tissue = "Lung"] was annoated with [tissue = "Immune system"], which I think this was correction, however, there are some cell types was annoated differently, how can I be sure which annoation was correct? Or if we can use [`tissue = c("Immune system", "lung")] to use both markers? Please see the attached figures.

using tissue immune system: https://drive.google.com/file/d/1Tja4EH9YPJXNwGq4ewlXWZbvPD5uTXIY/view?usp=sharing
using tissue lung: https://drive.google.com/file/d/1zx1ER9ay9jxqWZ6o8VYyeqMliMrsDGY9/view?usp=sharing

**Comment by IanevskiAleksandr** [comment]
If you are analyzing lung tissue, it is recommended to use the lung annotation dataset. In some cases, certain cell clusters in "Lung-based" annotations may be marked as "Immune system" cells. In these instances, you can reannotate the cells using the `tissue = "Immune system"` parameter to gain deeper resolution.

When dealing with a large unknown cell type, it can be challenging to determine the appropriate ScType annotation. To address this, you should identify the most differentially expressed genes (DEGs) for this cluster (or its subclusters) and search the literature to determine their potential cell type. If after checking DEGs, this large cluster cells express T-cell markers, it is appropriate to use `tissue = "Immune system"` annotations. However, it is important to avoid mixing annotations and strictly use correspondind cell type annotations.

**Comment by wisRen** [comment]
That's very kind of you. Thanks for your response.
