### ISSUE TITLE
Does adapting this to use with scATACseq make sense, with coordinates instead of genes?

### ISSUE THREAD

**Issue by ahdee** [IanevskiAleksandr/sc-type#37]
Hi I'm wondering if this sounds a bit strange or do you think it will work. 

We have 10x scATACseq the data structure essentially is the same only difference is that instead of genes they are coordinates. 

```
chr1-9811-10709    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ...... 

chr1-180671-181852 . . . . . . . . . 2 . . . . . . . . . . . . . 2 . . . . . . . . . . . . . . . . . . . . . . . . . . . ......
```
I plan to SCT transform this and on the excel sheet database add in coordinates instead of genes for "cell type" I want to enrich for.  

Would this work or even make sense? 

thanks.

**Comment by IanevskiAleksandr** [comment]
Dear @ahdee,

Yes, this should work.

BR,
Aleksandr
