### ISSUE TITLE
Malignant cells?

### ISSUE THREAD

**Issue by SirKuikka** [IanevskiAleksandr/sc-type#40]
Hi,

Thanks for developing this tool. How do I detect the malignant and non-malignant cells with this tool? The README makes no reference to this.

**Comment by SirKuikka** [comment]
I saw this response in two of the earlier issues. 

"We indeed had our own function to determine malignant/healthy cells. Even though, this feature (SNV calling) was initially available, it was later disabled due to variations in BAM input file formats which made it difficult to create a versatile function. However, a new function is currently being developed that will be more flexible and ask only for scRNA-seq expression matrix as input. We anticipate that this new function for annotating malignant/healthy cells will be available in ~2 months."

**Comment by IanevskiAleksandr** [comment]
@SirKuikka The new tool, that includes auomated detection of the malignant/non-malignant cells  is called https://github.com/kris-nader/scTherapy. Although it hasn't been officially published yet, you are welcome to explore and try it out.

BR,
Aleksandr
