### ISSUE TITLE
Scaling Only Marker Genes

### ISSUE THREAD

**Issue by shahrozeabbas** [IanevskiAleksandr/sc-type#41]
Hello,

I had a quick question. In the case where we may want to annotate a dataset that has a large cell count (million or more cells), would it be valid to only scale genes from the db instead of all genes and then subsetting for only those marker genes? 

I think the scaled values won't be affected since it's per gene across all cells, but I just wanted to make sure in case there's something I am missing? If valid, would greatly reduce the amount of memory needed to run on a large dataset. 

Thanks!

**Comment by IanevskiAleksandr** [comment]
@shahrozeabbas Good question! ScType scales the data for each gene to normalize gene expression levels across different cells, so I do NOT see any problems with the approach you suggest:)

BR,
Aleksandr
