### ISSUE TITLE
Cannot open the connection to  gene_sets_prepare.R

### ISSUE THREAD

**Issue by Daisy-Chilin** [IanevskiAleksandr/sc-type#50]
Hi. I've been having trouble loading  `gene_sets_prepare.R` and `sctype_score_.R`.  See error below:
```
Error in file(filename, "r", encoding = encoding): cannot open the connection to 'https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/R/gene_sets_prepare.R'
Traceback:

1. source("https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/R/gene_sets_prepare.R")
2. file(filename, "r", encoding = encoding)
```

When copying and pasting the URL onto a web browser i get this :

![Screen Shot 2024-02-05 at 3 10 26 PM](https://github.com/IanevskiAleksandr/sc-type/assets/88690145/babfac89-bc1a-4842-b225-444e6a214e15)

Do you know what's happening? Thanks!

**Comment by IanevskiAleksandr** [comment]
Dear @Daisy-Chilin ,

Please try using another network, just tested, it works fine.

BR,
Aleksandr
