### ISSUE TITLE
General question about the logic of the tool

### ISSUE THREAD

**Issue by Flu09** [IanevskiAleksandr/sc-type#54]
I want to ask about gene symbol 1 (list of present markers) and gene symbol 2 (list of absent markers).  

Are genes in this column need to be all present? or all absent? just asking about the logic of the tool. 

Thank you so much

**Comment by IanevskiAleksandr** [comment]
Dear @Flu09,

gene symbol 2 (list of negative/absent markers) is optional column and can be empty.

BR,
Aleksandr

**Comment by Flu09** [comment]
perhaps i did not make myself clear. My question is regarding the logic of the tool. is it all or none concept. The + genes need to be all present and the - genes absent need to be all absent in the cluster in order to be assigned as a certain celltype?

 what happens if just some of the genes are present or some are absent, will the cell assignment still go through as the same celltype? or it will start searching in the other cell types and their markers first? 
 
 I will greatly appreciate your help.

**Comment by kris-nader** [comment]
hi @Flu09 ,
sctype will score based on the common genes between scTypeDB and your dataset. Not all the genes in scTypeDB need to be included in your dataset. Of course, the more of an overlap the better.

**Comment by IanevskiAleksandr** [comment]
Dear @Flu09 ,

ScType does not strictly require all positive marker genes to be present and all negative ones to be absent for a cell to be classified as a specific type. It uses a comparative and statistical approach to assign cell types, even when only some markers are present or absent. 
Please refer to original publication for more information.

BR,
Aleksandr
