### ISSUE TITLE
Automatic detection of tissue type

### ISSUE THREAD

**Issue by jenny-gerbracht** [IanevskiAleksandr/sc-type#7]
Dear Aleksandr,

Thank you for sharing this helpful tool!

I had a question regarding the function "auto_detect_tissue_type" which I wanted to run on my own dataset. The script auto_detect_tissue_type.R contains the pbmc object (lines 25 and 26). I wondered whether this is intended or whether the function should accept a custom seurat object as an argument instead. When I provided my seurat object to the script it ran fine and predicted the correct tissue type for my data.

Thanks,
Jennifer

**Comment by IanevskiAleksandr** [comment]
It was fixed.

Kind regards,
Aleksandr
