### ISSUE TITLE
Perform automated annotation for virally infected cells

### ISSUE THREAD

**Issue by casparkfc** [IanevskiAleksandr/sc-type#70]
Hi, I would like to add some viral marker gene to the sctype database excel file and then perform the automated annotation but somehow that just would not work as the viral gene marker were regarded as non-approved gene symbol. How can I solve this?

```
db_ <- "humanandviralmarkergenes.xlsx"
tissue <- “Liver"
gs_list <- gene_sets_prepare(db_, tissue)
Warning messages:
1: In checkGeneSymbols(markers_all) : x contains non-approved gene symbols
2: In checkGeneSymbols(markers_all) : x contains non-approved gene symbols
```

Thanks

**Comment by IanevskiAleksandr** [comment]
Dear @casparkfc ,

You should modify gs_list before running scType function.

BR,
Aleksandr
