### ISSUE TITLE
Sc-type app and database not accessible

### ISSUE THREAD

**Issue by ewafula** [IanevskiAleksandr/sc-type#71]
@IanevskiAleksandr @kris-nader,

You mind checking your scptype app/database is no longer accessible. Every web search engine is blocks it as a security risk, espcially folks who work using institutional computers where they cannot bypass the security firewall. 
![Screenshot 2024-12-03 at 7 48 20 AM](https://github.com/user-attachments/assets/265aa6be-538b-42e2-9ee9-654a38b2e4be)

**Comment by yxwucq** [comment]
same
